import {dirname} from 'node:path';
import {fileURLToPath} from 'node:url';

import {FlatCompat} from '@eslint/eslintrc';

const compat = new FlatCompat({baseDirectory: dirname(fileURLToPath(import.meta.url))});

/**
 * ESLint configuration.
 *
 * `next/core-web-vitals` plus the TypeScript rules. Type correctness is already enforced by
 * `tsc --noEmit` with `strict` and `noUncheckedIndexedAccess`, so this layer is here for the
 * things the compiler cannot see: hook dependency arrays, accessibility, and Next-specific
 * mistakes such as navigating with a raw anchor.
 */
const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // `next-env.d.ts` is generated by Next on every build and is gitignored; linting it only
    // ever reports Next's own triple-slash directives.
    ignores: ['.next/**', 'node_modules/**', 'src/lib/abi/**', 'next-env.d.ts'],
  },
  {
    rules: {
      // Generated ABI modules are large `as const` literals; nothing else should use `any`.
      '@typescript-eslint/no-explicit-any': 'error',
      // Unused values are usually a leftover, but allow the `_`-prefixed convention for
      // deliberately discarded destructured entries.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none'},
      ],
    },
  },
];

export default config;
